# Generated by Django 4.1.4 on 2022-12-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='author',
            field=models.CharField(blank=True, default='Неизвестен', max_length=255, verbose_name='Автор'),
        ),
    ]
