# Generated by Django 4.1.4 on 2022-12-19 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_maincontent_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите ваше имя', max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите вашу фамилию', max_length=40, verbose_name='Фамилия')),
                ('birth', models.DateField(blank=True, help_text='Введите дату рождения', verbose_name='Дата рождения')),
                ('username', models.CharField(blank=True, help_text='Введите ваш никнейм', max_length=40, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Введите правильный адрес')], verbose_name='E-mail')),
                ('text', models.TextField(blank=True, verbose_name='Текст обращения')),
                ('grade', models.PositiveSmallIntegerField(default=5, help_text='Оценка от 0 до 10', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
